// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'input-text': string;
  'input-text__hint-wrapper': string;
  'input-text__title': string;
  'input-text__title-active': string;
  'input-text__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
