// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header__dropdown_catalog': string;
  'header__left': string;
  'header__left__logo': string;
  'header__left__title': string;
  'header__navbar': string;
  'header__navbar__menu_item': string;
  'header__right': string;
  'header__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
