// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hint__icon': string;
  'hint__icon--error': string;
  'hint__icon--info': string;
  'hint__icon--ok': string;
  'hint__icon--warning': string;
  'hint__inner': string;
  'hint__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
